// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUCJnWzlPPrZ89D21Tjbob7jQIJeV9jyg',
    appId: '1:1090572935761:web:48c7d61c48b688c59e8e70',
    messagingSenderId: '1090572935761',
    projectId: 'chat-app-e0beb',
    authDomain: 'chat-app-e0beb.firebaseapp.com',
    storageBucket: 'chat-app-e0beb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDupFhhXp0h5QH8ocTfg3C7YMrnt67sFKw',
    appId: '1:1090572935761:android:ca3b500d79d7f3fa9e8e70',
    messagingSenderId: '1090572935761',
    projectId: 'chat-app-e0beb',
    storageBucket: 'chat-app-e0beb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBivnK94ofxmOGGQLvj22EFzOlveTCd0zo',
    appId: '1:1090572935761:ios:03d11763476097049e8e70',
    messagingSenderId: '1090572935761',
    projectId: 'chat-app-e0beb',
    storageBucket: 'chat-app-e0beb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBivnK94ofxmOGGQLvj22EFzOlveTCd0zo',
    appId: '1:1090572935761:ios:03d11763476097049e8e70',
    messagingSenderId: '1090572935761',
    projectId: 'chat-app-e0beb',
    storageBucket: 'chat-app-e0beb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}